[project]
name = "fxai-toolkit"
description = "凤希全能节点，多资源批量管理器，无限长视频生成必备"
authors = [{name = "凤希AI", email = "15810208908@qq.com"}]
version = "1.0.1"
license = "MIT" 


[project.urls]
Repository = "https://github.com/fxai666/fxai-toolkit"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/fxai666/fxai-toolkit/wiki"
"Bug Tracker" = "https://github.com/fxai666/fxai-toolkit/issues"

[tool.comfy]
PublisherId = "fxai"
DisplayName = "凤希全能节点"
Icon = "https://www.fxai.site/img/logo256.png"
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

